var MSG = {
  catLoadingBlocks: "Loading...",
  update: "update 2016.06.29",
  title: "Webduino Blockly Editor",
  gotoTutorials: "Tutorials",
  gotoWebSite: "Official site",
  cleanUpBlocks: "Clean up Blocks",
  exportImage: "Download image",
  userMenuDashboard: "Dashboard",
  userMenuTutorials: "Tutorials",
  userMenuWebSite: "Support",
  userMenuLogout: "Logout",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  sampleTooltip: "Load Sample blocks.",
  demoTooltip: "Web demo area",
  openJsbin: "Open Code editor",
  checkDeviceOnline: "Check device online status",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catExec: "Delay",
  catRepeat: "Repeat",
  catBoard: "Board",
  catPin: "I/O Pins",
  catLed: "Led",
  catRelay: "Relay",
  catRGBLed: "RGBLed",
  catUltraSonic: "Ultra Sonic",
  catDht: "DHT",
  catButton: "Button",
  catShock: "Shock",
  catPir: "PIR Detect",
  catSound: "Sound Detect",
  catBuzzer: "Buzzer",
  catServo: "Servo",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  catConsole: "Console",
  catMathOther: "Math conversion",
  catTextLogic: "Text Logic",
  backIndex: "Webduino Blockly Tutorials",
  demoTitle: "Blockly Demo Area",
  catTutorials: "Blockly",
  linkToBin: "Let's Coding",
  catDatabase: "Data base",
  catFirebase: "Firebase",
  catCarTest: "Car (2)",
  catCar: "Car (1)",
  catFish: "Fly Fish",
  catBasic: "Basic Blocks",
  catWebduino: "Webduino Blocks",
  catMenu1: "Components",
  catMenu2: "Sensors",
  catMenu3: "Toies",
  catSpeech: "Speech",
  catSpeak: "Speak",
  catMobile: "Mobild",
  catTracking: "Tracking",
  catKeyCode: "Keyboard",
  catPlus: "Advanced",
  catStandard: "Standard",
  catMax7219: "LED Matrix",
  catPhotocell: "Photocell",
  catSoil: "Soil",
  catIRRecv: "IR Recv",
  catIRLed: "IR Launch",
  catADXL345: "ADXL345",
  catRFID: "RFID",
  catJoystick: "Joystick",
  catDemo: "Web Demo",
  catDemoText: "Show Text",
  catDemoLight: "Click Button",
  catDemoImage: "Control Image",
  catDemoArea: "Area Color",
  catDemoButton: "Button",
  catDemoRange: "Range",
  catDemoYoutube: "YouTube",
  catDemoTracking: "Tracking",
  catDemoController: "Controller",
  demoAreaTitle: "Web Demo",
  demoAreaChoose: "Choose:",
  demoAreaSelect1: "Show Text",
  demoAreaSelect2: "Click Light",
  demoAreaSelect3: "Control Image",
  demoAreaSelect4: "Area color",
  demoAreaSelect5: "Button",
  demoAreaSelect6: "Range",
  demoAreaSelect7: "Youtube",
  demoAreaSelect8: "Tracking",
  demoAreaSelect9: "Controller",
  demoAreaBtn1: "Button 1",
  demoAreaBtn2: "Button 2",
  demoAreaBtn3: "Button 3",
  demoAreaBtn4: "Button 4",
  demoAreaBtn5: "Button 5",
  demoAreaYoutube1: "YouTube video is displayed at the top",
  demoAreaYoutube2: "Must import: ",
  samples1:"Basic Samples",
  samples1_1:"LED",
  samples1_2:"RGB LED",
  samples1_3:"Buzzer",
  samples1_4:"Servo",
  samples1_5:"LED Matrix",
  samples2:"Sensors",
  samples2_1:"Ultra Sonic",
  samples2_2:"DHT",
  samples2_3:"Sound Detect",
  samples2_4:"PIR Detect",
  samples2_5:"PhotoCell",
  samples2_6:"Soil moisture",
  samples2_7:"ADXL 345",
  samples2_8:"RFID",
  samples3:"I/O",
  samples3_1:"2 LED",
  samples3_2:"RGB LED",
  samples4:"Youtube",
  samples4_1:"RFID + Youtube",
  samples4_2:"Button + Youtube",
  samples4_3:"Ultra Sonic + Youtube",
  samples5:"Advanced",
  samples5_1:"Virtual Controler",
  samples5_2:"Speech + Light",
  samples5_3:"Face + Light",
  samples5_4:"Parking sensors",
  samples5_5:"Toycar (keyboard)",
  samples5_6:"Toycar (Controler)",
  samples5_7:"DHT + Firbase",
  samples5_8:"RFID + Firbase",
  samples5_9:"DHT + LED Matrix",
  samples5_10:"Clock",
  samples6:"Many Boards",
  samples6_1:"Soil + LED",
  samples6_2:"Ultra Sonic + Matrix"
};
