var MSG = {
  update: "update 2015.10.20",
  title: "Webduino Blockly Editor",
  gotoTutorials: "Tutorials",
  gotoWebSite: "Official site",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Delete all %1 blocks?",
  trashTooltip: "Discard all blocks.",
  demoTooltip: "Web Demo",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catExec: "Delay",
  catRepeat: "Repeat",
  catBoard: "Board",
  catLed: "Led",
  catRelay: "Relay",
  catRGBLed: "RGBLed",
  catUltraSonic: "Ultra Sonic",
  catDht: "DHT",
  catButton: "Button",
  catShock: "Shock",
  catPir: "PIR Detect",
  catSound: "Sound Detect",
  catBuzzer: "Buzzer",
  catServo: "Servo",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  catConsole: "Console",
  backIndex: "Webduino Blockly Tutorials",
  demoTitle: "Blockly Demo Area",
  catTutorials: "Blockly",
  linkToBin: "Let's Coding",
  catDatabase: "Data base",
  catFirebase: "Firebase",
  catCarTest: "Car (2)",
  catCar: "Car (1)",
  catFish: "Fly Fish",
  catMenu1: "Components",
  catMenu2: "Sensors",
  catMenu3: "Toies",
  catSpeech: "Speech",
  catKeyCode: "Keyboard",
  catPlus: "Advanced",
  catStandard: "Standard",
  catMax7219: "LED Matrix",
  catPhotocell: "Photocell",
  catIRRecv: "IR Recv",
  catIRLed: "IR Launch",
  catADXL345: "ADXL345",
  catJoystick: "Joystick",
  catDemo: "Web Demo",
  catDemoText: "Show Text",
  catDemoLight: "Click Button",
  catDemoImage: "Control Image",
  catDemoArea: "Area Color",
  catDemoButton: "Button",
  catDemoYoutube: "YouTube",
  demoAreaTitle: "Web Demo",
  demoAreaChoose: "Choose:",
  demoAreaSelect1: "Show Text",
  demoAreaSelect2: "Click Light",
  demoAreaSelect3: "Control Image",
  demoAreaSelect4: "Area color",
  demoAreaSelect5: "Button",
  demoAreaSelect6: "Range",
  demoAreaSelect7: "Youtube",
  demoAreaBtn1: "Button 1",
  demoAreaBtn2: "Button 2",
  demoAreaBtn3: "Button 3",
  demoAreaBtn4: "Button 4",
  demoAreaBtn5: "Button 5",
  demoAreaYoutube1: "YouTube video is displayed at the top",
  demoAreaYoutube2: "Must import: "
};
