var MSG = {
  title: "Webduino Blockly 編輯器",
  gotoTutorials: "前往教學範例",
  blocks: "積木",
  linkTooltip: "儲存積木組並提供連結。",
  runTooltip: "於工作區中執行積木組所定義的程式。",
  badCode: "程式錯誤：\n%1",
  timeout: "超過最大執行數。",
  discard: "刪除共%1個積木？",
  trashTooltip: "捨棄所有積木。",
  catLogic: "邏輯",
  catLoops: "迴圈",
  catMath: "數學式",
  catText: "文字",
  catLists: "列表",
  catColour: "顏色",
  catVariables: "變量",
  catFunctions: "流程",
  catExec: "延遲 & 執行",
  catBoard: "開發板",
  catLed: "LED 燈",
  catRelay: "繼電器",
  catRGBLed: "三色 LED",
  catUltraSonic: "超音波",
  catDht: "溫濕度",
  catButton: "按鈕開關",
  catShock: "震動開關",
  catPir: "人體紅外線",
  catSound: "聲音偵測",
  catBuzzer: "蜂鳴器",
  catServo: "伺服馬達",
  listVariable: "列表",
  textVariable: "文字",
  httpRequestError: "命令出現錯誤。",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "未能載入您保存的檔案。或許它是由其他版本的Blockly創建？",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。",
  catConsole: "控制台",
  backIndex: "返回 Webduino 積木教學",
  demoTitle: "Blockly 範例測試區",
  catTutorials: "教學積木",
  linkToBin: "程式編輯",
  catDatabase: "資料庫",
  catFirebase: "Firebase",
  update: "update 2015.9.1",
  catCarTest: "自走車 (2)",
  catCar: "自走車 (1)",
  catFish: "飛天魚",
  catBasic:"基本積木",
  catWebduino:"Webduino 積木",
  catMenu1: "元件模組",
  catMenu2: "傳感器",
  catMenu3: "玩具應用",
  catPlus: "進階控制"
};
