var MSG = {
  lang: "zh-hant",
  catLoadingBlocks: "載入積木",
  update: "update 2017.12.01",
  title: "(體驗版) Webduino Blockly 編輯器",
  gotoCloud:"前往 Webudino 雲端平台！",
  gotoTutorials: "教學範例",
  gotoWebSite: "官方網站",
  cleanUpBlocks: "整理積木",
  exportImage: "下載圖片",
  userMenuDashboard: "專案管理",
  userMenuTutorials: "教學",
  userMenuApiDocs: "API 文件",
  userMenuDemos:"關卡練習",
  userMenuWebSite: "官網",
  userMenuLogout: "登出",
  blocks: "積木",
  linkTooltip: "儲存並產生連結",
  qrcodeTooltip: "產生即時預覽 QR code",
  runTooltip: "執行程式",
  stopRunTooltip: "停止執行",
  badCode: "程式錯誤：\n%1",
  timeout: "超過最大執行數",
  trashTooltip: "刪除所有積木",
  sampleTooltip: "載入範例積木",
  demoTooltip: "網頁互動區域",
  openJsbin: "打開程式編輯",
  checkDeviceOnline: "檢查裝置狀態",
  catLogic: "邏輯",
  catLoops: "迴圈",
  catMath: "數學式",
  catText: "文字",
  catLists: "列表",
  catColour: "顏色",
  catVariables: "變數",
  catFunctions: "流程",
  catExec: "等待",
  catRepeat: "狀態切換",
  catBoard: "開發板",
  catPin: "I/O 腳位",
  catLed: "LED 燈",
  catRelay: "繼電器",
  catRGBLed: "三色 LED",
  catUltraSonic: "超音波",
  catDht: "溫濕度",
  catButton: "按鈕開關",
  catShock: "震動開關",
  catPir: "人體紅外線",
  catSound: "聲音偵測",
  catBuzzer: "蜂鳴器",
  catServo: "伺服馬達",
  listVariable: "列表",
  textVariable: "文字",
  httpRequestError: "命令出現錯誤。",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "未能載入您保存的檔案。或許它是由其他版本的Blockly創建？",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。",
  catConsole: "控制台",
  catMathOther: "數值轉換",
  catTextLogic: "文字邏輯",
  backIndex: "返回 Webduino 積木教學",
  demoTitle: "Blockly 範例測試區",
  catTutorials: "教學積木",
  linkToBin: "程式編輯",
  catDatabase: "資料庫",
  catFirebase: "Firebase",
  catCarTest: "自走車",
  catFish: "飛天魚",
  catBasic: "基本積木",
  catWebduino: "Webduino 積木",
  catBoardGroup: "開發板控制",
  catMenu1: "發光元件",
  catMenu2: "輸入輸出",
  catMenu3: "環境偵測",
  catMenu4: "無線感應",
  catMenu5: "玩具及馬達",
  catSpeech: "語音聲控",
  catSpeak: "語音朗讀",
  catMobile: "行動裝置",
  catTracking: "影像辨識",
  catKeyCode: "鍵盤行為",
  catPlus: "進階功能",
  catStandard: "基本功能",
  catLED5x5: "全彩點距陣",
  catMax7219: "LED 點矩陣",
  catPhotocell: "光敏(可變)電阻",
  catSoil: "土壤濕度偵測",
  catIRRecv: "紅外線接收",
  catIRLed: "紅外線發射",
  catADXL345: "三軸加速度計",
  catRFID: "RFID",
  catJoystick: "搖桿",
  catDemo: "網頁互動",
  catDemoText: "顯示文字",
  catDemoLight: "點擊燈泡",
  catDemoImage: "控制圖片",
  catDemoArea: "顏色調整",
  catDemoButton: "按鈕行為",
  catDemoRange: "拉霸操作",
  catDemoYoutube: "YouTube",
  catDemoTracking: "影像追蹤",
  catDemoController: "遙控器",
  demoAreaTitle: "網頁互動測試",
  demoAreaChoose: "請選擇互動方式：",
  demoAreaSelect1: "顯示文字",
  demoAreaSelect2: "點擊燈泡",
  demoAreaSelect3: "控制圖片",
  demoAreaSelect4: "顏色調整",
  demoAreaSelect5: "按鈕行為",
  demoAreaSelect6: "拉霸操作",
  demoAreaSelect7: "Youtube",
  demoAreaSelect8: "影像追蹤",
  demoAreaSelect9: "遙控器",
  demoAreaColor: "選擇顏色：",
  demoAreaBtn1: "按鈕 1",
  demoAreaBtn2: "按鈕 2",
  demoAreaBtn3: "按鈕 3",
  demoAreaBtn4: "按鈕 4",
  demoAreaBtn5: "按鈕 5",
  demoAreaSlider: "拉霸：",
  demoAreaSliderValue: "數值：",
  demoAreaYoutube1: "YouTube 影片會顯示在上方",
  demoAreaYoutube2: "必須另外載入：",
  demoAreaRemoteDisplay: "顯示",
  samples1:"基礎操作",
  samples1_1:"LED",
  samples1_2:"全彩 LED",
  samples1_3:"蜂鳴器",
  samples1_4:"伺服馬達",
  samples1_5:"LED 點矩陣",
  samples2:"傳感器應用",
  samples2_1:"超音波偵測距離",
  samples2_2:"偵測環境溫濕度",
  samples2_3:"偵測聲音",
  samples2_4:"偵測人體紅外線",
  samples2_5:"偵測環境光線",
  samples2_6:"偵測土壤濕度",
  samples2_7:"偵測三軸加速度",
  samples2_8:"偵測 RFID 識別碼",
  samples3:"I/O 腳位",
  samples3_1:"操控兩顆 LED",
  samples3_2:"操控全彩 LED",
  samples4:"Youtube 應用",
  samples4_1:"RFID 切換影片",
  samples4_2:"按鈕開關控制播放",
  samples4_3:"超音波控制播放速度",
  samples5:"進階應用",
  samples5_1:"網頁虛擬遙控器",
  samples5_2:"聲控電燈",
  samples5_3:"人臉追蹤控制電燈",
  samples5_4:"倒車雷達",
  samples5_5:"自走車 ( 鍵盤 )",
  samples5_6:"自走車 ( 虛擬遙控器 )",
  samples5_7:"資料庫記錄溫濕度",
  samples5_8:"RFID 簡易門禁系統",
  samples5_9:"LED 點矩陣顯示濕度",
  samples5_10:"鬧鐘 ( 蜂鳴器 + 點矩陣 )",
  samples6:"開發板連動",
  samples6_1:"土壤濕度 + LED",
  samples6_2:"超音波 + LED 點矩陣"
};
