var MSG = {
  update: "update 2015.11.04",
  title: "Webduino Blockly 編輯器",
  gotoTutorials: "教學範例",
  gotoWebSite: "官方網站",
  cleanUpBlocks: "整理積木",
  exportImage: "下載圖片",
  userMenuDashboard: "專案管理",
  userMenuTutorials: "教學",
  userMenuWebSite: "資訊",
  userMenuLogout: "登出",
  blocks: "積木",
  linkTooltip: "儲存並產生連結",
  runTooltip: "執行組合",
  badCode: "程式錯誤：\n%1",
  timeout: "超過最大執行數",
  discard: "刪除共%1個積木？",
  trashTooltip: "刪除所有積木",
  demoTooltip: "網頁互動區域",
  openJsbin: "打開程式編輯",
  checkDeviceOnline: "檢查裝置狀態",
  catLogic: "邏輯",
  catLoops: "迴圈",
  catMath: "數學式",
  catText: "文字",
  catLists: "列表",
  catColour: "顏色",
  catVariables: "變量",
  catFunctions: "流程",
  catExec: "等待",
  catRepeat: "重複",
  catBoard: "開發板",
  catPin: "I/O 腳位",
  catLed: "LED 燈",
  catRelay: "繼電器",
  catRGBLed: "三色 LED",
  catUltraSonic: "超音波",
  catDht: "溫濕度",
  catButton: "按鈕開關",
  catShock: "震動開關",
  catPir: "人體紅外線",
  catSound: "聲音偵測",
  catBuzzer: "蜂鳴器",
  catServo: "伺服馬達",
  listVariable: "列表",
  textVariable: "文字",
  httpRequestError: "命令出現錯誤。",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "未能載入您保存的檔案。或許它是由其他版本的Blockly創建？",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。",
  catConsole: "控制台",
  catMathOther: "數值轉換",
  catTextLogic: "文字邏輯",
  backIndex: "返回 Webduino 積木教學",
  demoTitle: "Blockly 範例測試區",
  catTutorials: "教學積木",
  linkToBin: "程式編輯",
  catDatabase: "資料庫",
  catFirebase: "Firebase",
  catCarTest: "自走車 (2)",
  catCar: "自走車 (1)",
  catFish: "飛天魚",
  catBasic: "基本積木",
  catWebduino: "Webduino 積木",
  catMenu1: "元件模組",
  catMenu2: "傳感器",
  catMenu3: "玩具應用",
  catSpeech: "語音聲控",
  catTracking: "影像辨識",
  catKeyCode: "鍵盤行為",
  catPlus: "進階功能",
  catStandard: "基本功能",
  catMax7219: "LED 點矩陣",
  catPhotocell: "光敏(可變)電阻",
  catIRRecv: "紅外線接收",
  catIRLed: "紅外線發射",
  catADXL345: "三軸加速度計",
  catRFID: "RFID",
  catJoystick: "搖桿",
  catDemo: "網頁互動",
  catDemoText: "顯示文字",
  catDemoLight: "點擊燈泡",
  catDemoImage: "控制圖片",
  catDemoArea: "顏色調整",
  catDemoButton: "按鈕行為",
  catDemoRange: "拉霸操作",
  catDemoYoutube: "YouTube",
  catDemoTracking: "影像追蹤",
  demoAreaTitle: "網頁互動測試",
  demoAreaChoose: "請選擇互動方式：",
  demoAreaSelect1: "顯示文字",
  demoAreaSelect2: "點擊燈泡",
  demoAreaSelect3: "控制圖片",
  demoAreaSelect4: "顏色調整",
  demoAreaSelect5: "按鈕行為",
  demoAreaSelect6: "拉霸操作",
  demoAreaSelect7: "Youtube",
  demoAreaSelect8: "影像追蹤",
  demoAreaBtn1: "按鈕 1",
  demoAreaBtn2: "按鈕 2",
  demoAreaBtn3: "按鈕 3",
  demoAreaBtn4: "按鈕 4",
  demoAreaBtn5: "按鈕 5",
  demoAreaYoutube1: "YouTube 影片會顯示在上方",
  demoAreaYoutube2: "必須另外載入："
};
