MSG.title = "Webduino Blockly Chapter 13-4 : Switching Effects on LED Matrix";
MSG.subTitle = "Chapter 13-4 : Switching Effects on LED Matrix";
MSG.demoDescription = "Click on the buttons below to switch the effects on LED matrix. (Click on the following link, generating codes.)";
MSG.btn1 = "Button 1";
MSG.btn2 = "Button 2";
MSG.btn3 = "Button 3";
MSG.btnStop = "Stop";
MSG.btnOff = "Turn off";
MSG.generatorTitle = "Webduino LED Matrix Code Generator"
