MSG.title = "Webduino Blockly 关卡 2：红绿灯控制";
MSG.subTitle = "关卡 2：红绿灯控制";
MSG.demoDescription = "点选按钮，切换三色 LED 灯的颜色";
MSG.red = "Red";
MSG.green = "Green";
MSG.blue = "Blue";
MSG.clear = "Clear";
MSG.stageHelp = "我们每天都会看到路口的红绿灯，有没有想过自己也可以设计一个红绿灯呢？我们需要的是一片开发板加一颗三色 LED 灯。\n\n首先，你必须将三色 LED 灯中的 Ｖ 接到开发板上 3.3Ｖ 的位置，R、G、B 接到指定脚位。\n\n接着我们来想想，如果我们希望三色 LED 一开始不会发亮，并且让网页互动区下方的展示区域呈现黑色该怎么设定呢？\n\n完成 LED 灯开始时的设定后，我们还要设定当我们按下不同颜色的按钮（Red、Green、Blue、Ｃlear）时，LED 灯和展示区域会出现如同按钮标示的颜色。(Clear 会出现黑色、关闭 LED 灯)。";
MSG.demoTitle = "网页互动区";