MSG.title = "Webduino Blockly 關卡 2：紅綠燈控制";
MSG.subTitle = "關卡 2：紅綠燈控制";
MSG.demoDescription = "點選按鈕，切換三色 LED 燈的顏色";
MSG.red = "Red";
MSG.green = "Green";
MSG.blue = "Blue";
MSG.clear = "Clear";
MSG.stageHelp = "我們每天都會看到路口的紅綠燈，有沒有想過自己也可以設計一個紅綠燈呢？我們需要的是一片開發板加一顆三色 LED 燈。\n\n首先，你必須將三色 LED 燈中的 Ｖ 接到開發板上 3.3Ｖ 的位置，R、G、B 接到指定腳位。\n\n接著我們來想想，如果我們希望三色 LED 一開始不會發亮，並且讓網頁互動區下方的展示區域呈現黑色該怎麼設定呢？\n\n完成 LED 燈開始時的設定後，我們還要設定當我們按下不同顏色的按鈕（Red、Green、Blue、Ｃlear）時，LED 燈和展示區域會出現如同按鈕標示的顏色。(Clear 會出現黑色、關閉 LED 燈)。";
MSG.demoTitle = "網頁互動區";